<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * Creates comprehensive archetypes for each resource type to populate
     * the library with diverse options for community sharing.
     */
    public function up(): void
    {
        // Check if we're using MySQL or PostgreSQL
        $driver = DB::connection()->getDriverName();
        
        // Define archetypes for each resource type
        $archetypes = $this->getArchetypesData();
        
        foreach ($archetypes as $archetype) {
            // Check if archetype with same name and resource already exists
            $exists = DB::table('archetypes')
                ->where('name', $archetype['name'])
                ->where('resource', $archetype['resource'])
                ->exists();
            
            if (!$exists) {
                DB::table('archetypes')->insert($archetype);
            }
        }
        
        // Note: This migration adds comprehensive archetypes for all resource types
        // TOOL: 5 additional archetypes
        // MATERIAL: 18 archetypes
        // LABOR: 8 archetypes
        // RIDESHARE: 8 archetypes
        // FURNITURE: 12 archetypes
        // KITCHEN: 12 archetypes
        // ELECTRONICS: 12 archetypes
        // SPORTS: 16 archetypes
        // OUTDOOR: 15 archetypes
        // PARTY: 12 archetypes
        // BOOKS: 10 archetypes
        // OTHER: 12 archetypes
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Get all archetype names we added
        $archetypeNames = array_column($this->getArchetypesData(), 'name');
        
        DB::table('archetypes')
            ->whereIn('name', $archetypeNames)
            ->delete();
    }

    /**
     * Get archetypes data for all resource types
     */
    private function getArchetypesData(): array
    {
        $now = now()->format('Y-m-d H:i:s');
        
        return [
            // ============ TOOL (Additional) ============
            [
                'name' => 'Power Sander',
                'description' => 'Electric sander for smoothing wood surfaces',
                'notes' => 'Ideal for furniture refinishing projects',
                'code' => 'TOOL-SANDER',
                'modular' => '1',
                'resource' => 'TOOL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Jackhammer',
                'description' => 'Heavy-duty pneumatic hammer for breaking concrete',
                'notes' => 'Requires proper safety equipment',
                'code' => 'TOOL-JACKHAMMER',
                'modular' => '1',
                'resource' => 'TOOL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Concrete Mixer',
                'description' => 'Portable concrete mixer for small construction projects',
                'notes' => 'Electric powered, 3.5 cubic foot capacity',
                'code' => 'TOOL-MIXER',
                'modular' => '1',
                'resource' => 'TOOL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Welding Equipment',
                'description' => 'MIG welder for metal fabrication and repairs',
                'notes' => 'Includes welding helmet and gloves',
                'code' => 'TOOL-WELD',
                'modular' => '1',
                'resource' => 'TOOL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Post Hole Digger',
                'description' => 'Gas-powered auger for digging fence post holes',
                'notes' => 'Perfect for deck or fence installation',
                'code' => 'TOOL-AUGER',
                'modular' => '1',
                'resource' => 'TOOL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ MATERIAL ============
            [
                'name' => 'Lumber - 2x4',
                'description' => 'Standard dimensional lumber for construction',
                'notes' => 'Various lengths available',
                'code' => 'MAT-LUMBER-2X4',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Lumber - 4x4',
                'description' => 'Post timber for structural support',
                'notes' => 'Pressure treated options available',
                'code' => 'MAT-LUMBER-4X4',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Plywood Sheets',
                'description' => 'Standard plywood for sheathing and projects',
                'notes' => 'Available in various thicknesses',
                'code' => 'MAT-PLYWOOD',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Concrete Bags',
                'description' => 'Quick-setting concrete mix',
                'notes' => '80lb bags for posts and footings',
                'code' => 'MAT-CONCRETE',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Mulch',
                'description' => 'Organic mulch for landscaping',
                'notes' => 'Bagged or bulk delivery available',
                'code' => 'MAT-MULCH',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Gravel',
                'description' => 'Crushed stone for drainage and landscaping',
                'notes' => 'Various sizes available',
                'code' => 'MAT-GRAVEL',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Sand',
                'description' => 'Play sand or masonry sand',
                'notes' => 'For playgrounds or masonry work',
                'code' => 'MAT-SAND',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Paint - Interior',
                'description' => 'Interior latex paint',
                'notes' => 'Various colors available',
                'code' => 'MAT-PAINT-INT',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Paint - Exterior',
                'description' => 'Exterior latex paint',
                'notes' => 'Weather-resistant formula',
                'code' => 'MAT-PAINT-EXT',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Insulation Rolls',
                'description' => 'Fiberglass insulation for walls and attics',
                'notes' => 'R-value varies by product',
                'code' => 'MAT-INSULATION',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Drywall Sheets',
                'description' => 'Standard drywall for interior walls',
                'notes' => '1/2 inch standard',
                'code' => 'MAT-DRYWALL',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Tile - Ceramic',
                'description' => 'Ceramic floor and wall tile',
                'notes' => 'Various sizes and styles',
                'code' => 'MAT-TILE-CERAMIC',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Brick - Standard',
                'description' => 'Standard red clay brick',
                'notes' => 'For walls and patios',
                'code' => 'MAT-BRICK',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Paver Stones',
                'description' => 'Concrete pavers for patios and walkways',
                'notes' => 'Interlocking design',
                'code' => 'MAT-Pavers',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Topsoil',
                'description' => 'Quality topsoil for gardening and landscaping',
                'notes' => 'Screened and nutrient-rich',
                'code' => 'MAT-TOPSOIL',
                'modular' => '1',
                'resource' => 'MATERIAL',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ LABOR ============
            [
                'name' => 'General Helper',
                'description' => 'Assist with various tasks and projects',
                'notes' => 'Physical labor assistance',
                'code' => 'LABOR-HELPER',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Carpenter Assistant',
                'description' => 'Help with woodworking and carpentry projects',
                'notes' => 'Experience with tools preferred',
                'code' => 'LABOR-CARPENTER',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Paint Helper',
                'description' => 'Assistance with painting projects',
                'notes' => 'Prep work and cleanup included',
                'code' => 'LABOR-PAINT',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Garden Helper',
                'description' => 'Assistance with landscaping and gardening',
                'notes' => 'Planting, weeding, and maintenance',
                'code' => 'LABOR-GARDEN',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Move Assistant',
                'description' => 'Help with moving furniture and boxes',
                'notes' => 'Heavy lifting assistance',
                'code' => 'LABOR-MOVE',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Cleaner - Deep Clean',
                'description' => 'Thorough cleaning service',
                'notes' => 'Includes appliances, windows, and detailed cleaning',
                'code' => 'LABOR-CLEAN',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Yard Work Service',
                'description' => 'Lawn mowing and general yard maintenance',
                'notes' => 'Includes leaf removal and edging',
                'code' => 'LABOR-YARD',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Handyman Service',
                'description' => 'General repairs and small fixes',
                'notes' => 'Minor plumbing, electrical, and carpentry',
                'code' => 'LABOR-HANDY',
                'modular' => '1',
                'resource' => 'LABOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ RIDESHARE ============
            [
                'name' => 'Pickup Truck',
                'description' => 'Pickup truck for hauling and transport',
                'notes' => '5.5-6.5 ft bed, can tow trailers',
                'code' => 'RIDE-PICKUP',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'SUV',
                'description' => 'Sport utility vehicle for passenger transport',
                'notes' => 'Seats 5-7, good for groups',
                'code' => 'RIDE-SUV',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Van - Cargo',
                'description' => 'Cargo van for moving furniture and items',
                'notes' => 'Large cargo space, easy loading',
                'code' => 'RIDE-VAN-CARGO',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Van - Passenger',
                'description' => 'Passenger van for group transport',
                'notes' => 'Seats 7-12 passengers',
                'code' => 'RIDE-VAN-PASS',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Sedan',
                'description' => 'Standard sedan for daily transport',
                'notes' => 'Fuel efficient, seats 5',
                'code' => 'RIDE-SEDAN',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Airport Pickup',
                'description' => 'Transportation to/from airport',
                'notes' => 'Includes luggage assistance',
                'code' => 'RIDE-AIRPORT',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Event Transportation',
                'description' => 'Transport to events and gatherings',
                'notes' => 'Weddings, parties, concerts',
                'code' => 'RIDE-EVENT',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Grocery Run',
                'description' => 'Help with grocery shopping and delivery',
                'notes' => 'Includes shopping assistance',
                'code' => 'RIDE-GROCERY',
                'modular' => '1',
                'resource' => 'RIDESHARE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ FURNITURE ============
            [
                'name' => 'Folding Table',
                'description' => 'Portable folding table for events',
                'notes' => '6ft or 8ft lengths available',
                'code' => 'FURN-TABLE-FOLD',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Folding Chairs',
                'description' => 'Stackable folding chairs',
                'notes' => 'Set of 10 or more',
                'code' => 'FURN-CHAIR-FOLD',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Cocktail Tables',
                'description' => 'High cocktail tables for mingling',
                'notes' => '30 inch height',
                'code' => 'FURN-TABLE-COCKTAIL',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Chiavari Chairs',
                'description' => 'Elegant wedding and event chairs',
                'notes' => 'Gold, silver, or white finishes',
                'code' => 'FURN-CHAIR-CHIAVARI',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Tents - Small',
                'description' => '10x10 or 10x20 popup tent',
                'notes' => 'For small gatherings',
                'code' => 'FURN-TENT-SMALL',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Tents - Large',
                'description' => '20x40 or larger event tent',
                'notes' => 'For large gatherings and weddings',
                'code' => 'FURN-TENT-LARGE',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Dining Table',
                'description' => 'Large dining table for dinner parties',
                'notes' => 'Seats 8-10 people',
                'code' => 'FURN-TABLE-DINING',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Buffet Table',
                'description' => 'Sideboard/buffet for food service',
                'notes' => 'Includes serving stations',
                'code' => 'FURN-TABLE-BUFFET',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Couch',
                'description' => 'Sofa or couch seating',
                'notes' => 'Various styles available',
                'code' => 'FURN-COUCH',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Office Desk',
                'description' => 'Work desk for home office',
                'notes' => 'Standard or standing desk',
                'code' => 'FURN-DESK-OFFICE',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Bookshelf',
                'description' => 'Storage bookshelf',
                'notes' => 'Various sizes available',
                'code' => 'FURN-BOOKSHELF',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'TV Stand',
                'description' => 'Entertainment center TV stand',
                'notes' => 'Fits up to 65 inch TV',
                'code' => 'FURN-TVSTAND',
                'modular' => '1',
                'resource' => 'FURNITURE',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ KITCHEN ============
            [
                'name' => 'Catering Warming Tray',
                'description' => 'Electric warming tray for food service',
                'notes' => 'Keeps food at serving temperature',
                'code' => 'KITCHEN-WARM',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Chafing Dish Set',
                'description' => 'Stainless steel chafing dishes',
                'notes' => 'For buffet style serving',
                'code' => 'KITCHEN-CHAFING',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Coffee Urn',
                'description' => 'Large capacity coffee maker',
                'notes' => 'Makes 30-100 cups',
                'code' => 'KITCHEN-COFFEE',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Blender',
                'description' => 'Commercial grade blender',
                'notes' => 'For smoothies and frozen drinks',
                'code' => 'KITCHEN-BLENDER',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Food Processor',
                'description' => 'Large food processor',
                'notes' => 'For chopping, slicing, and shredding',
                'code' => 'KITCHEN-FOODPROC',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Kitchen Knife Set',
                'description' => 'Professional chef knife set',
                'notes' => 'Includes sharpening steel',
                'code' => 'KITCHEN-KNIVES',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Cutting Boards',
                'description' => 'Set of plastic cutting boards',
                'notes' => 'Various sizes, food safe',
                'code' => 'KITCHEN-CUTBOARD',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Serving Platters',
                'description' => 'Large serving platters and bowls',
                'notes' => 'For buffet and dinner service',
                'code' => 'KITCHEN-SERVE',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Plates and Cutlery Set',
                'description' => 'Dinner service for large groups',
                'notes' => 'Set of 20+ settings',
                'code' => 'KITCHEN-SERVICE',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Drink Dispenser',
                'description' => 'Beverage dispenser with stand',
                'notes' => 'For lemonade, punch, etc.',
                'code' => 'KITCHEN-DISPENSE',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Portable Stove',
                'description' => 'Propane camping stove',
                'notes' => '2-4 burners',
                'code' => 'KITCHEN-STOVE',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Electric Griddle',
                'description' => 'Large surface electric griddle',
                'notes' => 'For pancakes, burgers, etc.',
                'code' => 'KITCHEN-GRIDDLE',
                'modular' => '1',
                'resource' => 'KITCHEN',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ ELECTRONICS ============
            [
                'name' => 'Projector',
                'description' => 'HD projector for presentations and movies',
                'notes' => 'Includes screen',
                'code' => 'ELEC-PROJECTOR',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'PA System',
                'description' => 'Public address system with speakers',
                'notes' => 'For events and gatherings',
                'code' => 'ELEC-PA',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Microphone - Wireless',
                'description' => 'Wireless handheld microphone',
                'notes' => 'Includes receiver',
                'code' => 'ELEC-MIC-WIRELESS',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Speaker System',
                'description' => 'Portable speaker system',
                'notes' => 'Bluetooth enabled',
                'code' => 'ELEC-SPEAKER',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'TV - Large Screen',
                'description' => '55-75 inch TV for events',
                'notes' => 'HDMI compatible',
                'code' => 'ELEC-TV-LARGE',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Gaming Console',
                'description' => 'Video game console with controllers',
                'notes' => 'Includes popular games',
                'code' => 'ELEC-CONSOLE',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Drone',
                'description' => 'Camera drone for aerial photography',
                'notes' => 'Requires operator',
                'code' => 'ELEC-DRONE',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Camera - DSLR',
                'description' => 'Digital SLR camera',
                'notes' => 'Includes lenses',
                'code' => 'ELEC-CAMERA-DSLR',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Ring Light',
                'description' => 'LED ring light for photography/video',
                'notes' => 'Includes tripod',
                'code' => 'ELEC-RINGLIGHT',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Portable Speaker',
                'description' => 'Bluetooth portable speaker',
                'notes' => 'Waterproof options available',
                'code' => 'ELEC-SPEAKER-BT',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => ' karaoke Machine',
                'description' => 'Karaoke machine with microphone',
                'notes' => 'For parties and gatherings',
                'code' => 'ELEC-KARAOKE',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Power Bank',
                'description' => 'Portable charging station',
                'notes' => 'Multiple device charging',
                'code' => 'ELEC-POWERBANK',
                'modular' => '1',
                'resource' => 'ELECTRONICS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ SPORTS ============
            [
                'name' => 'Bicycle',
                'description' => 'Adult bicycle for riding',
                'notes' => 'Various sizes available',
                'code' => 'SPORTS-BIKE',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Kayak',
                'description' => 'Single or tandem kayak',
                'notes' => 'Includes paddles and life vests',
                'code' => 'SPORTS-KAYAK',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Canoe',
                'description' => 'Traditional canoe',
                'notes' => 'Seats 2-3 people',
                'code' => 'SPORTS-CANOE',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Paddleboard',
                'description' => 'Stand-up paddleboard',
                'notes' => 'Includes paddle and fin',
                'code' => 'SPORTS-PADDLEBOARD',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Tennis Rackets',
                'description' => 'Tennis racket set',
                'notes' => 'Includes balls',
                'code' => 'SPORTS-TENNIS',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Basketball',
                'description' => 'Basketball with pump',
                'notes' => 'Official size and weight',
                'code' => 'SPORTS-BASKETBALL',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Soccer Ball',
                'description' => 'Soccer ball with pump',
                'notes' => 'Size 5 regulation',
                'code' => 'SPORTS-SOCCER',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Golf Clubs',
                'description' => 'Full set of golf clubs',
                'notes' => 'Includes bag',
                'code' => 'SPORTS-GOLF',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Baseball Gloves',
                'description' => 'Baseball glove set',
                'notes' => 'Various sizes',
                'code' => 'SPORTS-BASEBALL',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Football Gear',
                'description' => 'Football equipment',
                'notes' => 'Helmets, pads, and ball',
                'code' => 'SPORTS-FOOTBALL',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Skateboard',
                'description' => 'Skateboard with safety gear',
                'notes' => 'Includes helmet and pads',
                'code' => 'SPORTS-SKATEBOARD',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Ice Skates',
                'description' => 'Figure or hockey skates',
                'notes' => 'Various sizes',
                'code' => 'SPORTS-SKATES',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Yoga Mat',
                'description' => 'Premium yoga mat',
                'notes' => 'Includes carrying strap',
                'code' => 'SPORTS-YOGA',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Exercise Bike',
                'description' => 'Stationary exercise bike',
                'notes' => 'With digital display',
                'code' => 'SPORTS-BIKE-EXERCISE',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Weights Set',
                'description' => 'Dumbbell and barbell weights',
                'notes' => 'Various weight options',
                'code' => 'SPORTS-WEIGHTS',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Trampoline',
                'description' => 'Backyard trampoline',
                'notes' => 'Safety enclosure included',
                'code' => 'SPORTS-TRAMPOLINE',
                'modular' => '1',
                'resource' => 'SPORTS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ OUTDOOR ============
            [
                'name' => 'Camping Tent',
                'description' => '2-4 person tent',
                'notes' => 'Easy setup, includes stakes',
                'code' => 'OUTDOOR-TENT',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Sleeping Bag',
                'description' => 'Warm sleeping bag',
                'notes' => 'Temperature rated',
                'code' => 'OUTDOOR-SLEEPBAG',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Camping Stove',
                'description' => 'Propane camping stove',
                'notes' => '2 burner',
                'code' => 'OUTDOOR-STOVE',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Cooler',
                'description' => 'Large insulated cooler',
                'notes' => 'Keeps ice for days',
                'code' => 'OUTDOOR-COOLER',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Camping Chair',
                'description' => 'Folding camping chair',
                'notes' => 'Includes cup holder',
                'code' => 'OUTDOOR-CHAIR',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Hammock',
                'description' => 'Camping hammock',
                'notes' => 'Includes straps',
                'code' => 'OUTDOOR-HAMMOCK',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Lantern',
                'description' => 'LED camping lantern',
                'notes' => 'Rechargeable or battery',
                'code' => 'OUTDOOR-LANTERN',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'First Aid Kit',
                'description' => 'Comprehensive first aid kit',
                'notes' => 'For outdoor activities',
                'code' => 'OUTDOOR-FIRSTAID',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Binoculars',
                'description' => 'Outdoor binoculars',
                'notes' => 'For bird watching and nature',
                'code' => 'OUTDOOR-BINOCULARS',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Backpack',
                'description' => 'Hiking backpack',
                'notes' => 'Various capacities',
                'code' => 'OUTDOOR-BACKPACK',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Portable Fire Pit',
                'description' => 'Propane or wood fire pit',
                'notes' => 'For outdoor gatherings',
                'code' => 'OUTDOOR-FIREPIT',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Camping Mattress',
                'description' => 'Inflatable camping mattress',
                'notes' => 'Self-inflating',
                'code' => 'OUTDOOR-MATTRESS',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Grill',
                'description' => 'Portable BBQ grill',
                'notes' => 'Propane or charcoal',
                'code' => 'OUTDOOR-GRILL',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Beach Umbrella',
                'description' => 'Large beach umbrella',
                'notes' => 'With sand anchor',
                'code' => 'OUTDOOR-UMBRELLA',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Lawn Games Set',
                'description' => 'Lawn games like cornhole, ladder ball',
                'notes' => 'For outdoor parties',
                'code' => 'OUTDOOR-LAWNGAMES',
                'modular' => '1',
                'resource' => 'OUTDOOR',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ PARTY ============
            [
                'name' => 'Disco Ball',
                'description' => 'Rotating disco ball with lights',
                'notes' => 'Includes motor and lights',
                'code' => 'PARTY-DISCO',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Disco Lights',
                'description' => 'Party light effects',
                'notes' => 'LED color changing',
                'code' => 'PARTY-LIGHTS',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Balloon Arch',
                'description' => 'Balloon arch framework',
                'notes' => 'Includes balloon pump',
                'code' => 'PARTY-BALLOON-ARCH',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Photo Booth Props',
                'description' => 'Photo booth prop set',
                'notes' => 'For birthday parties',
                'code' => 'PARTY-PROPS',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Party Hats',
                'description' => 'Festive party hats',
                'notes' => 'Various colors',
                'code' => 'PARTY-HATS',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Streamers',
                'description' => 'Colorful party streamers',
                'notes' => 'Various colors',
                'code' => 'PARTY-STREAMERS',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Party Tableware Set',
                'description' => 'Paper plates, cups, napkins',
                'notes' => 'Themed designs available',
                'code' => 'PARTY-TABLEWARE',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Piñata',
                'description' => 'Traditional party piñata',
                'notes' => 'Various shapes',
                'code' => 'PARTY-PINATA',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Fog Machine',
                'description' => 'Stage fog machine',
                'notes' => 'For party effects',
                'code' => 'PARTY-FOG',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Confetti Cannon',
                'description' => 'Electric confetti cannon',
                'notes' => 'For celebrations',
                'code' => 'PARTY-CONFETTI',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Cake Topper',
                'description' => 'Birthday cake topper',
                'notes' => 'Customizable',
                'code' => 'PARTY-CAKETOPPER',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Party Favors Set',
                'description' => 'Party favor bags and toys',
                'notes' => 'For goodie bags',
                'code' => 'PARTY-FAVORS',
                'modular' => '1',
                'resource' => 'PARTY',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ BOOKS ============
            [
                'name' => 'Cookbook Collection',
                'description' => 'Various recipe books',
                'notes' => 'Cooking and baking',
                'code' => 'BOOKS-COOKBOOK',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Gardening Books',
                'description' => 'Books on gardening and landscaping',
                'notes' => 'Plant care and design',
                'code' => 'BOOKS-GARDEN',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'DIY Home Improvement',
                'description' => 'Home repair and renovation guides',
                'notes' => 'Step by step instructions',
                'code' => 'BOOKS-DIY',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Children\'s Books',
                'description' => 'Kids story books collection',
                'notes' => 'Various ages',
                'code' => 'BOOKS-KIDS',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Textbooks - Math',
                'description' => 'Mathematics textbooks',
                'notes' => 'Various levels',
                'code' => 'BOOKS-MATH',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Textbooks - Science',
                'description' => 'Science textbooks',
                'notes' => 'Physics, chemistry, biology',
                'code' => 'BOOKS-SCIENCE',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Novels - Fiction',
                'description' => 'Fiction novel collection',
                'notes' => 'Bestsellers and classics',
                'code' => 'BOOKS-FICTION',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Car Manual',
                'description' => 'Vehicle repair manual',
                'notes' => 'Make and model specific',
                'code' => 'BOOKS-CAR',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Art Instruction Books',
                'description' => 'Drawing and painting guides',
                'notes' => 'Various mediums',
                'code' => 'BOOKS-ART',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Music Sheet Collection',
                'description' => 'Sheet music for instruments',
                'notes' => 'Various genres',
                'code' => 'BOOKS-MUSIC',
                'modular' => '1',
                'resource' => 'BOOKS',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],

            // ============ OTHER ============
            [
                'name' => 'Moving Boxes',
                'description' => 'Cardboard moving boxes',
                'notes' => 'Various sizes',
                'code' => 'OTHER-BOXES',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Bubble Wrap',
                'description' => 'Protective bubble wrap rolls',
                'notes' => 'For packing',
                'code' => 'OTHER-BUBBLEWRAP',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Hand Truck',
                'description' => 'Two-wheeled hand truck',
                'notes' => 'For moving heavy items',
                'code' => 'OTHER-HANDTRUCK',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Dolly',
                'description' => 'Furniture dolly',
                'notes' => 'For moving furniture',
                'code' => 'OTHER-DOLLY',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Storage Bins',
                'description' => 'Plastic storage containers',
                'notes' => 'Various sizes',
                'code' => 'OTHER-STORAGE',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Ladder - Step',
                'description' => 'Step ladder',
                'notes' => '4-8 foot height',
                'code' => 'OTHER-LADDER-STEP',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Wheelbarrow',
                'description' => 'Garden wheelbarrow',
                'notes' => 'For soil and mulch',
                'code' => 'OTHER-WHEELBARROW',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Garden Hose',
                'description' => 'Long garden hose',
                'notes' => 'With spray nozzle',
                'code' => 'OTHER-HOSE',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Pressure Washer',
                'description' => 'Gas or electric pressure washer',
                'notes' => 'For cleaning driveways and siding',
                'code' => 'OTHER-PRESSUREWASHER',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Sewing Machine',
                'description' => 'Electric sewing machine',
                'notes' => 'For alterations and projects',
                'code' => 'OTHER-SEWING',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Craft Supplies',
                'description' => 'Various craft supplies',
                'notes' => 'Paper, glue, scissors, etc.',
                'code' => 'OTHER-CRAFTS',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
            [
                'name' => 'Tools Set',
                'description' => 'General hand tool set',
                'notes' => 'Wrenches, screwdrivers, pliers',
                'code' => 'OTHER-TOOLS',
                'modular' => '1',
                'resource' => 'OTHER',
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => '1',
            ],
        ];
    }
};

